version: "3.9"
services:
  web:  
    image: jrodriguezs2020/snapstudy 
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/snapstudy
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=DAWWebapp09+
      - JWT_SECRET=snapstudy
      - AWS_S3_ACCESS_KEY_ID=change_me
      - AWS_S3_SECRET_ACCESS_KEY=change_me
      - GOOGLE_DRIVE_FOLDER=change_me
      - APPLICATION_MAIL=change_me
      - APPLICATION_PASS_MAIL=change_me
      - MAIL_TEMPLATE_PATH=change_me
      - CREDENTIALS_FILE_PATH=change_me
    depends_on:
      - db
    restart: on-failure
    volumes:
      - credentials:/usr/src/app/config
      - email:/usr/src/app/email

  db:
    image: mysql:8.0.22
    restart: always
    ports:
    - "3307:3306"
    environment:
      - MYSQL_DATABASE=snapstudy
      - MYSQL_ROOT_PASSWORD=DAWWebapp09+
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  credentials:
  email: