version: "3.9"
services:
  web:  
    image: jrodriguezs2020/snapstudy 
    ports:
      - "8443:8443"
    environment:
      - GOOGLE_DRIVE_FOLDER=change_me
      - APPLICATION_MAIL=change_me
      - APPLICATION_PASS_MAIL=change_me
      - MAIL_TEMPLATE_PATH=change_me
      - CREDENTIALS_FILE_PATH=change_me
      - AWS_OPENSEARCH_ENDPOINT=change_me
      - DB_USER=change_me
      - DB_URL=change_me
      - DB_PASSWORD=change_me
      - AWS_PROFILE=change_me
    depends_on:
      - db
    restart: on-failure
    volumes:
      - credentials:/usr/src/app/config
      - email:/usr/src/app/email
      - ~/.aws:/root/.aws

  db:
    image: mysql:8.0.22
    restart: always
    ports:
    - "3307:3306"
    environment:
      - MYSQL_DATABASE=snapstudy
      - MYSQL_ROOT_PASSWORD=DAWWebapp09+
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  credentials:
  email: