services:
  web:
    env_file: ".env"
    image: jrodriguezs2020/snapstudy 
    ports:
      - "8443:8443"
    environment:
      - MAIL_TEMPLATE_PATH=/usr/src/app/email/emailTemplate.html
      - DB_USER=admin
      - DB_PASSWORD=snapstudy
      - CREDENTIALS_FILE_PATH=/usr/src/app/config/credentials.json
    restart: on-failure
    volumes:
      - credentials:/usr/src/app/config
      - email:/usr/src/app/email

volumes:
  credentials:
  email: