AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 con Docker Compose (Java + Angular), usando SG y VPC por defecto

Parameters:
  DefaultSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID del default Security Group

  CredentialsS3Bucket:
    Description: Ruta S3 del archivo credentials.json
    Type: String

  KeyName:
    Description: Nombre del par de claves EC2
    Type: AWS::EC2::KeyPair::KeyName

  GOOGLEDRIVEFOLDER:
    Description: Carpeta de Google Drive para la app
    Type: String

  APPLICATIONMAIL:
    Description: Email de la aplicación
    Type: String

  APPLICATIONPASSMAIL:
    Description: Contraseña del email de la aplicación
    Type: String

  AWSOPENSEARCHENDPOINT:
    Description: Endpoint de OpenSearch AWS
    Type: String

  DBURL:
    Description: URL de la base de datos
    Type: String

Resources:
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref S3AccessRole

  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      RoleName: ec2-role
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${CredentialsS3Bucket}/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${CredentialsS3Bucket}
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ReadObject
                Resource:
                  - !Sub arn:aws:s3:::snapstudy-s3
                  - !Sub arn:aws:s3:::snapstudy-s3/*

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DefaultSecurityGroupId
      IpProtocol: tcp
      FromPort: 8443
      ToPort: 8443
      CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-015b1e8e2a6899bdb
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - default
      Tags:
        - Key: Name
          Value: JavaAngularDockerEC2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo dnf update -y
          sudo dnf install -y git mariadb105 docker
          sudo dnf install -y libxcrypt-compat

          sudo systemctl enable --now docker
          sudo usermod -aG docker ec2-user
          sudo usermod -aG wheel ec2-user

          # Docker Compose v1 (instalación manual)
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          cd /home/ec2-user
          sudo git clone https://github.com/codeurjc-students/2024-snap-study app
          cd app

          mysql -h ${DBURL} -u admin -p"snapstudy" < backup.sql
          sudo aws s3 cp s3://${CredentialsS3Bucket}/credentials.json /home/ec2-user/app/backend/credentials.json

          cd docker
          cat <<EOF | sudo tee .env
          GOOGLE_DRIVE_FOLDER=${GOOGLEDRIVEFOLDER}
          APPLICATION_MAIL=${APPLICATIONMAIL}
          APPLICATION_PASS_MAIL=${APPLICATIONPASSMAIL}
          AWS_OPENSEARCH_ENDPOINT=${AWSOPENSEARCHENDPOINT}
          DB_URL=${DBURL}
          EOF

          sudo chown -R ec2-user:ec2-user /home/ec2-user/app
          sudo docker-compose up -d


Outputs:
  InstancePublicIP:
    Description: IP pública de la instancia EC2
    Value: !GetAtt EC2Instance.PublicIp