AWSTemplateFormatVersion: '2010-09-09'
Description: OpenSearch domain for snapstudy

Parameters:
  OpenSearchDomainName:
    Type: String
    Default: snapstudy-opensearch

Resources:

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref OpenSearchDomainName
      EngineVersion: 'OpenSearch_2.17'
      ClusterConfig:
        InstanceCount: 1
        InstanceType: t3.small.search
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp3
        VolumeSize: 10
        Iops: 3000
        Throughput: 125
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::${AWS::AccountId}:user/snapstudy
                - arn:aws:iam::${AWS::AccountId}:role/snapstudy-lambda-execution-role
            Action:
              - es:ESHttpPost
              - es:ESHttpPut
              - es:ESHttpGet
              - es:ESHttpHead
            Resource:
              - !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchDomainName}
              - !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchDomainName}/*
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
      EncryptionAtRestOptions:
        Enabled: true
        UseAWSOwnedKey: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: false
      # Public access and IPv4 only, no VPC config needed

Outputs:
  OpenSearchEndpoint:
    Value: !GetAtt OpenSearchDomain.Endpoint
    Description: The endpoint of the OpenSearch domain