AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear una Lambda que se active con eventos de SQS

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: snapstudy-lambda-execution-dlq-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicyDlq
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:snapstudy-text-process-sqs-test-dlq
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: 
                  - arn:aws:s3:::snapstudy-s3
                  - arn:aws:s3:::snapstudy-s3/*
              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpGet
                Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/snapstudy-opensearch

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: snapstudy-text-process-lambda-test-dlq
      Runtime: python3.9
      Handler: lambda_dlq_code.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: snapstudy-artifacts
        S3Key: lambda_dlq_code.zip
      Timeout: 180
      MemorySize: 128

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      EventSourceArn: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:snapstudy-text-process-sqs-test-dlq
      FunctionName: !GetAtt LambdaFunction.Arn
      Enabled: true

Outputs:
  LambdaFunctionArn:
    Description: ARN de la función Lambda
    Value: !GetAtt LambdaFunction.Arn