AWSTemplateFormatVersion: "2010-09-09"
Description: "Agregar regla inbound al SG para permitir acceso MySQL (puerto 3306) desde una IP específica."

Parameters:
  MyIPAddress:
    Description: "IP CIDR format (xxxxxxxx/32)"
    Type: String

  TargetSecurityGroupId:
    Description: "Security Group ID"
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  MySQLIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref TargetSecurityGroupId
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      CidrIp: !Ref MyIPAddress