AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear una SQS y configurar eventos de S3

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: snapstudy-text-process-sqs-test

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: arn:aws:s3:::snapstudy-s3

Outputs:
  QueueURL:
    Description: URL de la cola SQS creada
    Value: !Ref SQSQueue
  QueueARN:
    Description: ARN de la cola SQS creada
    Value: !GetAtt SQSQueue.Arn