AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear una SQS y configurar eventos de S3

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: snapstudy-text-process-sqs-test
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SQSQueueDlq.Arn
        maxReceiveCount: 1

  SQSQueueDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: snapstudy-text-process-sqs-test-dlq
      VisibilityTimeout: 180

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:DeleteMessage
              - sqs:GetQueueUrl
              - sqs:PurgeQueue
              - sqs:ChangeMessageVisibility
            Resource: !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: arn:aws:s3:::snapstudy-s3

  SQSQueueDlqPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueueDlq
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:DeleteMessage
              - sqs:GetQueueUrl
              - sqs:PurgeQueue
              - sqs:ChangeMessageVisibility
            Resource: !GetAtt SQSQueueDlq.Arn

Outputs:
  QueueURL:
    Description: URL de la cola SQS creada
    Value: !Ref SQSQueue
  QueueARN:
    Description: ARN de la cola SQS creada
    Value: !GetAtt SQSQueue.Arn
  DlqQueueURL:
    Description: URL de la cola SQS DLQ creada
    Value: !Ref SQSQueueDlq
  DlqQueueARN:
    Description: ARN de la cola SQS DLQ creada
    Value: !GetAtt SQSQueueDlq.Arn